# Generated by Django 3.2.13 on 2022-05-06 11:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('PostalCode', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('Segment', models.CharField(max_length=32)),
                ('Country', models.CharField(max_length=32)),
                ('City', models.CharField(max_length=32)),
                ('State', models.CharField(max_length=32)),
                ('Region', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('CustomerID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('CustomerName', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductID', models.CharField(max_length=32, primary_key=True, serialize=False, unique=True)),
                ('Category', models.CharField(max_length=32)),
                ('SubCategory', models.CharField(max_length=32)),
                ('ProductName', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('OrderID', models.CharField(max_length=32)),
                ('OrderDate', models.DateField()),
                ('ShipDate', models.DateField()),
                ('ShipMode', models.CharField(max_length=32)),
                ('Sales', models.FloatField()),
                ('Quantity', models.IntegerField()),
                ('Discount', models.FloatField()),
                ('Profit', models.FloatField()),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('ProductID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
            ],
            options={
                'unique_together': {('OrderID', 'CustomerID', 'ProductID')},
            },
        ),
        migrations.CreateModel(
            name='customer_postal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CustomerID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.customer')),
                ('PostalCode', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.address')),
            ],
            options={
                'unique_together': {('CustomerID', 'PostalCode')},
            },
        ),
    ]
